version: "2"

linters:
  enable:
    - sloglint
    - gocritic
    - goconst
    - asasalint
    - contextcheck
    - unparam
    - thelper
    - unconvert
    - nolintlint
  settings:
    sloglint:
      # Enforce not mixing key-value pairs and attributes.
      # Default: true
      no-mixed-args: false
      # Enforce using methods that accept a context.
      # Default: false
      context: "scope"
      # Enforce using static values for log messages.
      # Default: false
      static-msg: true
      # Enforce using constants instead of raw keys.
      # Default: false
      no-raw-keys: true
      # Enforce a single key naming convention.
      # Values: snake, kebab, camel, pascal
      # Default: ""
      key-naming-case: snake
      # Enforce putting arguments on separate lines.
      # Default: false
      args-on-sep-lines: true
